### ISSUE TITLE
Refactor any live or pending components to use `withLabel` property

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#2073]
Until recently, the component API did not natively support access a prop value's label, so we implemented workarounds like, `label, value: { label, value }`, but this structure is not compatible with the upcoming UI refresh (smurt inputs).

So we've added a new property to the component API, `withLabel`. We need to update all live and pending components to use this new property asap.

Here is an example of the implementation, since we haven't yet updated our docs: https://github.com/PipedreamHQ/pipedream/blob/c8f168de85813ceee84b32da46e53b2c41daff21/components/spotify/spotify.app.mjs#L26

Context from Slack: https://pipedream-users.slack.com/archives/C01E5KCTR16/p1642536943036900?thread_ts=1642536367.036100&cid=C01E5KCTR16

**Comment by dannyroosevelt** [comment]
known apps w/ components that need to be refactored:
- [ ] Spotify
- [ ] Zoom
- [ ] Reddit
- [ ] Dropbox
- [ ] Hubspot
- [ ] Zoho CRM
- [ ] Shopify

**Comment by js07** [comment]
I rechecked Zoho CRM and Shopify props with stringified object values. Since their values have additional information required by components that use them, and they are already stringified, I don't think they need to be refactored.

For reference:
- Zoho CRM's [`moduleInfo`](https://github.com/PipedreamHQ/pipedream/blob/7da9a3a6909511b73f1f464353cd60fe406db23a/components/zoho_crm/sources/common/http-based/custom-module.mjs#L8) prop has option values of the form [`JSON.stringify({ type, name })`](https://github.com/PipedreamHQ/pipedream/blob/7da9a3a6909511b73f1f464353cd60fe406db23a/components/zoho_crm/sources/common/http-based/custom-module.mjs#L26-L29)
- Shopify's [`eventTypes`](https://github.com/PipedreamHQ/pipedream/blob/7da9a3a6909511b73f1f464353cd60fe406db23a/components/shopify/shopify.app.js#L174) prop has option values of the form [`JSON.stringify({ filter, verb })`](https://github.com/PipedreamHQ/pipedream/blob/7da9a3a6909511b73f1f464353cd60fe406db23a/components/shopify/shopify.app.js#L9-L12)

**Comment by vellames-turing** [comment]
FYI:
Reddit is almost done, I found some bugs on some old sources, I am fixing it. Next will be Dropbox. I expect to finish it all this week

**Comment by vellames-turing** [comment]
Reddit ready for QA, Dropbox under new review

**Comment by vellames-turing** [comment]
@dannyroosevelt FYI: All my apps were refactored to use `withLabel`

**Comment by js07** [comment]
Status of the PRs that resolve this issue:
- [x] Spotify (**Merged**): #2071 
- [x] Zoom (**Merged**): #1866 
- [ ] Reddit (**Ready for QA**): #1865 
- [ ] Dropbox (**Ready for QA**): #1956 
- [ ] Hubspot (**Ready for QA**): #1419

**Comment by dannyroosevelt** [comment]
Great! So there is no outstanding dev work, right? That's all done and just needs to be QA'd and merged?

**Comment by js07** [comment]
Yes, that's all the dev work barring any QA issues. I think this issue can be closed after the remaining 3 PRs are merged.

**Comment by dannyroosevelt** [comment]
Great, thank you!
